### ISSUE TITLE
[问题]: 最新版的延迟动作问题

### ISSUE THREAD

**Issue by hyhaochen233** [InsinuateProjects/TrMenu#108]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2021-12-07 18:08:24)

| Server OS: Windows 10 amd64 10.0
| Server software: git-CatServer-1.12.2-119130c (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_172

| TrMenu: 3.0
Installed Plugins: 
· CMI - 9.0.4.6 (0 KB)
· CMIEInjector - 1.0.2.1 (0 KB)
· CMILib - 1.0.4.2 (0 KB)
· Citizens - 2.0.28-SNAPSHOT (build 2357) (0 KB)
· DragonCore - 2.4.7 (0 KB)
· LuckPerms - 5.3.86 (0 KB)
· Multiverse-Core - 1.1 (0 KB)
· NyEconomy - 1.4.5-SNAPSHOT (0 KB)
· OnlineReward - 1.3.5-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.9.2 (0 KB)
· PokeLevel - 1.0 (0 KB)
· PokemonAPI - 3.2.0.12-SNAPSHOT (0 KB)
· PokemonPapiPro - 1.1.0 (0 KB)
· ProtocolLib - 4.4.0 (0 KB)
· TrChat - 1.90-R3 (0 KB)
· TrHologram - 2.4-pre23 (0 KB)
· TrMenu - 3.0 (0 KB)
· Vault - 1.7.3-b131 (0 KB)

### 🔍 详细的描述

```
1. 在使用最新版的 trmenuv3.0 无法使用 延迟动作 进行操作
2. 在trmenu rc4版本中 不修改配置文件的情况下 可以使用
```

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```
  'B':
    display:
      material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWU1OTVlMTQzNDg2YmJkZDk4YjJiNTYyMzAwZDRjNjk4ZTZhNTNhNWFhM2ZhMzI4Zjc0Y2I4MzkwOWUwODhjNCJ9fX0='
      name: '&f&l▶ &e&l随身治疗机'
    actions:
      all:
      - 'close'
      - 'title: &f&l正在治疗你的宝可梦 `&f■ &8■ ■ ■ ■` 20 60 15'
      - 'delay: 20'
      - 'title: &f&l正在治疗你的宝可梦 `&f■ ■ &8■ ■ ■` 20 60 15'
      - 'delay: 20'
      - 'title: &f&l正在治疗你的宝可梦 `&f■ ■ ■ &8■ ■` 20 60 15'
      - 'delay: 20'
      - 'title: &f&l正在治疗你的宝可梦 `&f■ ■ ■ ■ &8■` 20 60 15'
      - 'delay: 20'
      - 'title: &f&l正在治疗你的宝可梦 `&f■ ■ ■ ■ ■` 20 60 15'
      - 'delay: 20'
      - 'title: &f&l你的宝可梦治疗完成 &a&l宝可梦又可以战斗了 20 60 15'
      - 'delay: 20'
      - 'console: pokeheal %player_name%'
```
