### ISSUE TITLE
[Bug]: 最新一次构建，Break动作失效

### ISSUE THREAD

**Issue by Ling556** [InsinuateProjects/TrMenu#109]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

spigot1.16.5

### 🔍 Detailed description

最新一次“修复delay动作”的构建后，break动作无效

**Comment by QQ464944870** [comment]
i also have this problem

**Comment by Score2** [comment]
@Rubenicos

**Comment by Rubenicos** [comment]
This means that before the pull request #348 a set of actions like this would also fail at break action:
```yaml
actions:
  all:
    - condition: 'perm *permission.123'
      actions:
        - 'tell: &a1'
        - 'tell: &e2'
        - 'break'
        - 'tell: &c3'
```
So the problem is on Actions.kt?
