### ISSUE TITLE
[功能]: 可选菜单是否纯发包模式

### ISSUE THREAD

**Issue by Score2** [InsinuateProjects/TrMenu#127]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

```
1. 以此尝试修复间歇泉或其它有关冲突插件.
2. 以此兼容依赖bukkit inventory 操控的插件
```

### ⚙ 配置文件

菜单配置.yml
```yaml
Options:
    # 默认 true
    Pure-Packet: false
```
