### ISSUE TITLE
[问题]: 

### ISSUE THREAD

**Issue by SueFox** [InsinuateProjects/TrMenu#129]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-01-14 20:05:40)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Paper-1618 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 11.0.12.8

| TrMenu: 3.1.1
Installed Plugins: 
· AuthMe - 5.6.0-SNAPSHOT-b2510 (0 KB)
· Citizens - 2.0.28-SNAPSHOT (build 2391) (0 KB)
· CommandWhitelist - 1.2.3 (0 KB)
· DeluxeHub - 3.4.0 (0 KB)
· EastLandLog4jFixer - 1.0.4 (0 KB)
· GSigns - 6.6 (0 KB)
· LuckPerms - 5.3.86 (0 KB)
· PPRMB - 1.3.1-BETA (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· PlayerPoints - 3.1.1 (0 KB)
· ProtocolLib - 4.7.1-SNAPSHOT-b536 (0 KB)
· ScriptBlockPlus - 2.2.1 (0 KB)
· TrChat - 1.90-R5 (0 KB)
· TrHologram - 2.4-pre24 (0 KB)
· TrMenu - 3.1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· Vulcan - 2.2.7 (0 KB)
· XConomy - 2.13.5 (0 KB)
```

### 🔍 详细的描述

```
1. 某些菜单莫名其妙不能使用打开菜单的动作打开
```

### 🗄 服务端日志

```
无报错
```

### ⚙ 配置文件

```
  '-':
    display:
      material: '{"type":"STAINED_GLASS_PANE","data":13,"amount":64,"meta":{}}'
      shiny: 'true'
      name: "&3&l◆ &f&l返回&3&l ◆"
      lore:
        - ''
        - '&8[ &2·&8 ] &3任意点击 &f返回主菜单'
    actions:
      all: 
        - 'menu: 主菜单'
        - 'sound: BLOCK_LEVER_CLICK-1-2'

不止这一个
连action指令都无效
```
