### ISSUE TITLE
[Feature]: Add a zero amount of items.

### ISSUE THREAD

**Issue by RE4ERKA** [InsinuateProjects/TrMenu#130]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### 🔗 Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 🔍 Detailed description

This is what it should look like:
![image](https://user-images.githubusercontent.com/66727581/149541654-e01fea93-8443-4794-8685-0ab2ecf48da3.png)

It would be nice to add such a function by specifying "amount: 0". 

### ⚙ Configurations

```
Layout:
  - 'a'

Icons:
  'a':
    display:
      material: apple
      amount: 0
```
