### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by paulreob** [InsinuateProjects/TrMenu#144]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2022-02-05 06:32:55)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Purpur-1542 (MC: 1.18.1) (1.18.1-R0.1-SNAPSHOT)
| Java version: 17

| TrMenu: 3.1.1
Installed Plugins: 
· ArmorStandTools - 4.4.4 (0 KB)
· Essentials - 2.19.3-dev+8-a9585bb (0 KB)
· EssentialsChat - 2.19.3-dev+8-a9585bb (0 KB)
· EssentialsSpawn - 2.19.3-dev+8-a9585bb (0 KB)
· FakePlayers - 1.0-SNAPSHOT (0 KB)
· HMCCosmetics - 1.7.0 (0 KB)
· HomesGUI - 0.1.0 (0 KB)
· ItemsAdder - 2.5.5 (0 KB)
· LoneLibs - 1.0.16b (0 KB)
· LuckPerms - 5.3.3 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· ProtocolLib - 4.8.0-SNAPSHOT-b539 (0 KB)
· RPGhuds - 1.1.0 (0 KB)
· TrMenu - 3.1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· WorldEdit - 7.2.8+6008-1246d61 (0 KB)
· WorldGuard - 7.0.6+1cff55f (0 KB)

### 🔍 Detailed description

Hi, I am trying to use variables that I set it in the above menu, to use it in:

nbt: 
   CustomModelData: '{1}'
and also
mats: '{0}{model-data:{1}}}'
i am using it in several ways but none of these works even with javascript! xd

### 🗄 Server log

```

```

### ⚙ Configurations

```
Title:
  - 'cosmetic-dye'

Layout:
  - '########<'
  - '|       |'
  - '| - X + |'
  - '|       |'
  - '####*####'

# {0}         {1}
# {itemName} {CustomModelData}
Events:
  Open:
    - 'reset'
  Close:
    - 'del-args'

Icons:
  'X':
    display:
      mats: "{0}{dye:255,255,255}"
      nbt:
        CustomModelData: '{1}'
      lore:
        - '${witch.hat}'

Functions:
  witch:
    hat: vars("{1}")
```
```
title: "cosmetic-backpack"
Layout:
  - '         '
  - ' 0       '
  - '         '
  - '         '
  - '         '
Icons:
  '0':
    display:
      material: source:itemsadder:genkiru:witch_head{dye:255,255,255}
    actions:
      all:
        - 'sound: UI_BUTTON_CLICK-1-2'
        - "menu: Shop-Handler-Purchase leather_horse_armor 10004"


Functions:
  witch_head: |-
    function witch_head() {
      var display = source:itemsadder:genkiru:witch_head
      return display
    }
    witch_head()
    ```
