### ISSUE TITLE
[问题]: Events.Close触发open menu动作时“闪退”

### ISSUE THREAD

**Issue by TUCAOEVER** [InsinuateProjects/TrMenu#147]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-02-07 00:30:18)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Purpur-1171 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
| Java version: 16.0.2

| TrMenu: 3.1.1
Installed Plugins: 
· BetonQuest - 1.12.7 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2420) (0 KB)
· CrazyCrates - 1.10.1-RELEASE (0 KB)
· Essentials - 2.19.2 (0 KB)
· FastAsyncWorldEdit - 1.17-426;42035bd (0 KB)
· LuckPerms - 5.3.98 (0 KB)
· MMOItems - 6.7-SNAPSHOT (0 KB)
· MMOMana - 1.2.3 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· MythicLib - 1.3-R21-SNAPSHOT (0 KB)
· MythicMobs - 5.0.0-SNAPSHOT-9944578c (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 2.1.5-SNAPSHOT (0 KB)
· ProtocolLib - 4.7.1-SNAPSHOT-b536 (0 KB)
· Repuska - 2.8.8 (0 KB)
· ServerListPlus - 3.5.0-SNAPSHOT (0 KB)
· ServerTours - 1.6.9 (0 KB)
· ShopGUIPlus - 1.68.3 (0 KB)
· Skript - 2.6.1 (0 KB)
· TAB - 3.0.1 (0 KB)
· TrHologram - 2.4-pre24 (0 KB)
· TrMenu - 3.1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VoidGen - 2.2 (0 KB)
· WorldEditSUI - 1.7.2 (0 KB)
· WorldGuard - 7.0.5+3827266 (0 KB)
```

### 🔍 详细的描述

```
使用Events.Close时触发open menu动作组，菜单正常打开后被自动退出，呈现“闪退”错误，使用delay 1可暂时解决此问题。
```

### 🗄 服务端日志

```
无报错
```

### ⚙ 配置文件

```
Title:
  - '&lTest'

Title-Update: -1

TYPE: HOPPER
Shape:
  - ' A B '

Options:
  Lock-Player-Inv: true
  Transfer-Args: false
version
  Update-Inventory: false
  Force-Transfer-Args: 0

events:
  close:
    - 'open: 1'
```
