### ISSUE TITLE
[Bug]: ANVILL无法完成2或多次捕获

### ISSUE THREAD

**Issue by Dirt233** [InsinuateProjects/TrMenu#148]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2022-02-08 01:04:29)

| Server OS: Windows Server 2016 amd64 10.0
| Server software: git-Paper-1620 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_211

| TrMenu: 3.1.1
Installed Plugins: 
· AlwaysDay - 2.2.8 (0 KB)
· AnimationLib - 1.7.0 (0 KB)
· BBSToper - 3.6.7 (0 KB)
· CashCode - 1.7 (0 KB)
· ChairStairs - 1.1 (0 KB)
· Citizens - 2.0.27-SNAPSHOT (build 2302) (0 KB)
· CommandNPC - 1.9.1 (0 KB)
· DeluxeJoin - 2.9.2 (0 KB)
· DeluxeMenus - 1.13.3-Release (0 KB)
· FarmProtect - 1.9.0 (0 KB)
· GadgetsMenu - 5.0.6 (0 KB)
· GlobalExecute - 1.0.1 (0 KB)
· Helper - 1.0.0 (0 KB)
· HolographicDisplays - 2.4.9 (0 KB)
· Images - 2.2.3 (0 KB)
· ItemJoin - 5.2.1-RELEASE-b678 (0 KB)
· LiteBans - 2.8.13 (0 KB)
· LiteInvitation - 1.4.3-SNAPSHOT (0 KB)
· LobbyLevel - 1.0-Revamp (0 KB)
· LobbyPresents - 4.3 (0 KB)
· LuckPerms - 5.3.64 (0 KB)
· Mczf - 1.0.0-b20 (0 KB)
· MiaoChat - 2.0.0-git-be66b3b9a0c8a8f4a1ccc360671efededb8bdce1 (0 KB)
· MiaoScript - 0.17.0 (0 KB)
· MyCommand - 5.7.1 (0 KB)
· NametagEdit - 4.4.10 (0 KB)
· NickNamer - 3.18.6-SNAPSHOT (0 KB)
· NoCheatPlus - 3.17-SNAPSHOT-Updated-b129 (0 KB)
· NoJoinQuitMessage - 2.3.3 (0 KB)
· NoRain - 1.6 (0 KB)
· PacketListenerApi - 3.7.9-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerBalancerAddon - 2.3.1-SNAPSHOT (0 KB)
· PlayerCommands - 1.0.0 (0 KB)
· PlayerHider - 1.4 (0 KB)
· PlayerMention - 2.0 (0 KB)
· PlayerPoints - 2.1.5-SNAPSHOT (0 KB)
· ProtocolLib - 4.6.0 (0 KB)
· SQLibrary - 7.1 (0 KB)
· SimpleFly - 3.0 (0 KB)
· StopFallDamage - 1.0 (0 KB)
· SuperAntiChat - 1.0.0 (0 KB)
· TigerReports - 4.13.1 (0 KB)
· TpLogin - 3.1 (0 KB)
· TrMenu - 3.1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 4.1.1 (0 KB)
· ViaRewind - 2.0.2 (0 KB)
· ViaVersion - 4.1.1 (0 KB)
· VipSystem - 4.13 (0 KB)
· Void2Spawn - 1.1.0 (0 KB)
· WorldBorder - 1.8.7 (0 KB)
· WorldEdit - 6.1.9;caf0ad9 (0 KB)
· XConomy - 2.11.1 (0 KB)
· Yum - 2.9.5-git-18dc99e78ee6c087da72f944be32e90e5c93b3a5 (0 KB)

### 🔍 Detailed description

anvil容器无法完成2次或多次捕获

### 🗄 Server log

none

### ⚙ Configurations
```
all:
        - 'close'
        - 'sound: BLOCK_TRIPWIRE_ATTACH'
        - catcher:
            command:
              type: ANVIL
              start: 'actionbar: &a&l请写出内容! &f&l输入命令&7(不加/) &f&l格式如下 &3空格使用%n%代替 &3玩家名字使用%p%代替 &3多命令之间使用%d%代替 '
              cancel: 'actionbar: &8取消'
              end:
                - 'set-meta: command {meta:input}'
                - catcher:
                    number:
                      type: ANVIL
                      start: 'actionbar: &c&l请写出正常的数字'
                      cancel: 'actionbar: &8取消'
                      end:
                        - 'command: code create {meta:command} {meta:input}'
```
