### ISSUE TITLE
[Bug / Question]: 部分情况下菜单中 Icon 需要多次点击方能执行 / refresh 刷新菜单图标不成功

### ISSUE THREAD

**Issue by Yurinann** [InsinuateProjects/TrMenu#150]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-02-19 18:29:37)

| Server OS: Windows Server 2022 amd64 10.0
| Server software: git-Pufferfish-46 (MC: 1.18.1) (1.18.1-R0.1-SNAPSHOT)
| Java version: 17.0.2

| TrMenu: 3.1.4
Installed Plugins: 
· AdvancedCleaner - 1.4 (0 KB)
· AntiCombatLog - 2.2.5 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2517 (0 KB)
· BentoBox - 1.19.0 (0 KB)
· BetterEnchantBook - 0.3-BETA (0 KB)
· CMI - 9.1.1.2 (0 KB)
· CMILib - 1.1.1.0 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2471) (0 KB)
· InteractionVisualizer - 1.17.1.11 (0 KB)
· JonAPI - 1.1-c1 (0 KB)
· LightAPI - 3.5.2 (0 KB)
· LiteBans - 2.8.13 (0 KB)
· LiteSignIn - 1.5.6 (0 KB)
· LuckPerms - 5.4.4 (0 KB)
· MineResetLite - 4.13.0-VK (0 KB)
· MiniMOTD - 2.0.5 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· PPRMB - 1.4.0-BETA (0 KB)
· PVPRewards - 2.2 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.1.1 (0 KB)
· ProtocolLib - 4.8.0-SNAPSHOT-b540 (0 KB)
· QuickShop - 5.1.0.4 (0 KB)
· RainbowGzExpansion - 1.0.0 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· TAB - 3.1.0-pre1 (0 KB)
· TrChat - 1.90-R6 (0 KB)
· TrMenu - 3.1.4 (0 KB)
· UserPrefix - 2.4.1 (0 KB)
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· WorldBorderAPI - 1.181.2 (0 KB)
· WorldEdit - 7.2.9+e20e013 (0 KB)
· WorldGuard - 7.0.6+1cff55f (0 KB)
· XConomy - 2.15.2 (0 KB)
· exppond - 1.0.0 (0 KB)
```

### 🔍 详细的描述

```
1. 打开任意一个菜单
2. 点击任意一个图标
3. 部分情况下需要反复多次点击 (一般两次) 方可正常执行图标 actions; 使用 'refresh' / 'refresh: <icon>' 未成功刷新图标 display
```

### 🗄 服务端日志

```
无
```

### ⚙ 配置文件

```
Example:
  'G':
    display:
      material: copper_ingot
      name: '&a&l普通会员 &a永久 &7(未开通)'
      lore:
        - ''
        - '&f价格: &d50点券'
        - '&c您的点券不足!'
    icons:
      - condition: 'perm *rainbowgz.vip'
        display:
          material: copper_ingot
          name: '&a&l普通会员 &a永久 &7(已开通)'
          lore:
            - ''
            - '&f价格: &d50点券'
            - '&a您已购买!'
        actions:
          all:
            - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - condition: 'points *50'
        display:
          material: copper_ingot
          name: '&a&l普通会员 &a永久 &7(未开通)'
          lore:
            - ''
            - '&f价格: &d50点券'
            - '&a点击购买!'
        actions:
          all:
            - 'take-points: 50'
            - 'console: lp user %player_name% parent add vip'
            - 'tell color *"&a购买成功!"'
            - 'console: cmi broadcast 玩家 %player_name% 成功购买了普通会员!'
            - 'refresh'
            - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
```
