### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yuankun1** [InsinuateProjects/TrMenu#185]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

mohist-1.12.2-321-server
最新版本trmenu3.1.10
报告
https://timings.aikar.co/?id=64167aae87574f77bc0524f05ecd5cf2

### 🔍 Detailed description

```
1.  'A':
    update: [-1, 10, 15, -1]
    display:
       material: '<customskull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzdlOGNiNTdmZTc5MGU5NjVlM2NmYTZjNGZiYzE2ZTMyMjYyMTBkNjVmNTYxNGU4ODUzZmE5ZmI4NDA3NDQ0MSJ9fX0==>'
       name: '&a&l精灵世界'
       lore:
         - '&f&m======================'
         - '&6▸ &F在这里可以获得'
         - '&f无穷无尽的&a资源'
         - '&6▸ &f进行精灵&c对战&8/&a提升'
         - '&f更&6高级更强大的&4精灵'
         - '&f&m======================'
         - '&a左键传送 &6右键随机传送'
    actions:
      all: 'sound: ENTITY_ARROW_HIT_PLAYER-1-2'
      Left:
        - 'close'
        - 'command: warp 精灵世界'
      Right:
        - condition: 'money *10'    
          actions:
           - 'close'
           - 'title: &f&l<&e&l准备随机传送...&f&l>'
           - 'wait: 60'
           - 'Console: eco take %player_name% 10'
           - 'wait: 25'
           - 'title: &f≈[&b&l传送成功&f]&f≈ '
           - 'op: rt world'
          deny:
            - 'close'
            - 'title: &8&l<&c&l准备随机传送...&8&l>'
            - 'wait: 40'
            - 'title: &8<&e小樱提示&8> &6&l您的游戏币10不够随机传送'  
配置文件这样写 我发现我使用rt 随机传送不会影响tps
但是放到菜单Right 这样写 随机传送一次导致tps掉的很严重
trmenu 3.1.9就不会有事

### 🗄 Server log

```

```


### ⚙ Configurations

```

```
