### ISSUE TITLE
[问题]: 一个菜单的图标会跑到另一个菜单去

### ISSUE THREAD

**Issue by AwesomeDY** [InsinuateProjects/TrMenu#192]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-06-08 10:37:40)
 | Server OS: Windows Server 2016 amd64 10.0
 | Server software: git-Paper-794 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
 | Java version: 11
 | TrMenu: 3.1.10 Installed Plugins:
 · AdvancedBan - 2.3.0 (0 KB)
 · AncientGates - 2.5.1 (0 KB)
 · AntiAttack - 1.0.0 (0 KB)
 · ArmorstandPlugin - 0.1 (0 KB)
 · ArtMap - 3.9.8 (0 KB)
 · AttributePlus - 3.2.9 (0 KB)
 · AureliumSkills - Beta 1.3.4 (0 KB)
 · AuthMe - 5.6.0-beta2-b2453 (0 KB)
 · BanItem - 3.3.3 (0 KB)
 · BetterHeads - 1.3-BETA (0 KB)
 · BuildersWand - 2.23.0 (0 KB)
 · CMILib - 1.1.2.6 (0 KB)
 · Citizens - 2.0.29-SNAPSHOT (build 2540) (0 KB)
 · CleanMOTD - 0.2.7 (0 KB)
 · ClearLag - 3.2.2 (0 KB)
 · CoreProtect - 21.2 (0 KB)
 · CrazyAuctionsPlus - 1.2.1 (0 KB)
 · CrazyCrates - 1.10.2-Build#1 (0 KB)
 · DecentHolograms - 2.4.0 (0 KB)
 · DeluxeTags - 1.8.2-Release (0 KB)
 · DiceFurniture - 3.6.0 (0 KB)
 · DungeonPlus - 1.2.5 (0 KB)
 · EasyCommandBlocker - 1.4.2 (0 KB)
 · EpicCraftingsPlus - 7.10.2 (0 KB)
 · Essentials - 2.19.4 (0 KB)
 · EssentialsChat - 2.19.4 (0 KB)
 · EssentialsProtect - 2.19.4 (0 KB)
 · EssentialsSelectors - 1.5 (0 KB)
 · EssentialsSpawn - 2.19.4 (0 KB)
 · EssentialsTPClickAccept - 1.0.1-beta (0 KB)
 · FurnitureLib - 2.7.4 (0 KB)
 · GSit - 1.0.10 (0 KB)
 · HoloMobHealth - 2.2.5.15 (0 KB)
 · InteractionVisualizer - 1.17.2.7 (0 KB)
 · InteractiveChat - 4.1.4.14 (0 KB)
 · JukeBox - 1.20.6 (0 KB)
 · LightAPI - bukkit-5.2.0 (build SNAPSHOT) (0 KB)
 · LiteAnnouncer - 1.2.2 (0 KB)
 · LitePlaytimeRewards - 2.5.1 (0 KB)
 · LiteSignIn - 1.6.0 (0 KB)
 · LuckPerms - 5.4.21 (0 KB)
 · MeToo - 1.0.1 (0 KB)
 · Multiverse-Core - 4.3.1-b861 (0 KB)
 · MythicMobs - 4.14.1-47dddd45 (0 KB)
 · NBTAPI - 2.9.2 (0 KB)
 · NoteBlockAPI - 1.6.1-SNAPSHOT (0 KB)
 · OasisRecipe - 0.0.9-20220525 (0 KB)
 · OpenInv - 4.1.8 (0 KB)
 · Parkour - 6.7.1 (0 KB)
 · PlaceholderAPI - 2.11.1 (0 KB)
 · PlayerParticles - 8.1 (0 KB)
 · PlayerPoints - 3.2.4 (0 KB)
 · PlugManX - 2.3.0 (0 KB)
 · PointLogger - 1.0.2 (0 KB)
 · Pouvoir - 1.2.9 (0 KB)
 · ProtectionLib - 1.6 (0 KB)
 · ProtocolLib - 4.8.0 (0 KB)
 · QuickShop - 5.1.0.7 (0 KB)
 · Residence - 5.0.1.6 (0 KB)
 · Shopkeepers - 2.15.1 (0 KB)
 · SkinsRestorer - 14.1.15 (0 KB)
 · Slock - 1.3 (0 KB)
 · SuperVanish - 6.2.7 (0 KB)
 · TAB - 3.1.1 (0 KB)
 · TempFly - 3.1.7 (0 KB)
 · TrMenu - 3.1.10 (0 KB)
 · Vault - 1.7.3-b131 (0 KB)
 · VeinMiner - 1.17.10 (0 KB)
 · ViaVersion - 4.2.1 (0 KB)
 · ViewSlimeChunk - 1.0.1 (0 KB)
 · WorldEdit - 7.2.10+1742f98 (0 KB)
 · WorldGuard - 7.0.5+3827266 (0 KB)
 · ajLeaderboards - 2.5.3 (0 KB)
 · ntdLuckyBlock - 2.7.0-BETA (0 KB)
```

### 🔍 详细的描述

```
在一个菜单里面用menu动作跳转到另一个菜单，再从另一个菜单用menu跳转回去，那图标就会错位，另一个菜单的图标会跑到第一个菜单里面，但是actions没有改变，只改变了显示的物品
---
点击菜单的“返回主菜单”和“职业选择”俩按钮多弄几次就会触发，第一个菜单的图标会跑到第二个菜单里面去
```

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```
第一个Title: "&8职业选择: %player_name%"
Layout:
  - "####*####"
  - "#~#ABCDE#"
  - "# #FGHIJ#"
  - "# #KLMNO#"
  - "# #PQRST#"
  - "#########"
Icons:
  "#":
    display:
      material: BLACK_STAINED_GLASS_PANE
      name: " "
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
  "*":
    display:
      material: GRAY_STAINED_GLASS_PANE
      name: "&e返回主菜单"
    actions:
      all:
        - "close"
        - "menu: 主要菜单"
        - "sound: UI_BUTTON_CLICK-1-1"
  "~":
    update: 1
    refresh: 1
    display:
      material: "<head:%player_name%>"
      name: "&e个人信息"
      lore:
        - "&r"
        - "&8| &7当前职业: &6无"
        - "&8| &7重置价格: &e0$"
        - "&r"
        - "&8| &e&l✔快去选择职业吧"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
    icons:
      - condition: "perm *ap.战士"
        display:
          material: "<head:%player_name%>"
          name: "&e个人信息"
          lore:
            - "&r"
            - "&8| &7当前职业: &6战士"
            - "&8| &7重置价格: &e5000$"
            - "&r"
            - "&8| {ke: if money *5000 then *&e&l✔点击重置职业 else *&c&l✖你没有足够的金币}"
            - "&r"
          flags:
            - "HIDE_ENCHANTS"
            - "HIDE_ATTRIBUTES"
            - "HIDE_UNBREAKABLE"
            - "HIDE_POTION_EFFECTS"
            - "HIDE_DESTROYS"
            - "HIDE_PLACED_ON"
        actions:
          all:
            - "sound: UI_BUTTON_CLICK-1-1"
            - condition: "money *5000"
              actions:
                - "take-money: 5000"
                - "console: lp user %player_name% permission unset ap.战士"
                - "tell: &8[&6SYSTEM&8] &c职业已重置！"
                - "close"
              deny:
                - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法重置职业"
                - "close"
      - condition: "perm *ap.刺客"
        display:
          material: "<head:%player_name%>"
          name: "&e个人信息"
          lore:
            - "&r"
            - "&8| &7当前职业: &6刺客"
            - "&8| &7重置价格: &e5000$"
            - "&r"
            - "&8| {ke: if money *5000 then *&e&l✔点击重置职业 else *&c&l✖你没有足够的金币}"
            - "&r"
          flags:
            - "HIDE_ENCHANTS"
            - "HIDE_ATTRIBUTES"
            - "HIDE_UNBREAKABLE"
            - "HIDE_POTION_EFFECTS"
            - "HIDE_DESTROYS"
            - "HIDE_PLACED_ON"
        actions:
          all:
            - "sound: UI_BUTTON_CLICK-1-1"
            - condition: "money *5000"
              actions:
                - "take-money: 5000"
                - "console: lp user %player_name% permission unset ap.刺客"
                - "tell: &8[&6SYSTEM&8] &c职业已重置！"
                - "close"
              deny:
                - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法重置职业"
                - "close"
      - condition: "perm *ap.坦克"
        display:
          material: "<head:%player_name%>"
          name: "&e个人信息"
          lore:
            - "&r"
            - "&8| &7当前职业: &6坦克"
            - "&8| &7重置价格: &e5000$"
            - "&r"
            - "&8| {ke: if money *5000 then *&e&l✔点击重置职业 else *&c&l✖你没有足够的金币}"
            - "&r"
          flags:
            - "HIDE_ENCHANTS"
            - "HIDE_ATTRIBUTES"
            - "HIDE_UNBREAKABLE"
            - "HIDE_POTION_EFFECTS"
            - "HIDE_DESTROYS"
            - "HIDE_PLACED_ON"
        actions:
          all:
            - "sound: UI_BUTTON_CLICK-1-1"
            - condition: "money *5000"
              actions:
                - "take-money: 5000"
                - "console: lp user %player_name% permission unset ap.坦克"
                - "tell: &8[&6SYSTEM&8] &c职业已重置！"
                - "close"
              deny:
                - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法重置职业"
                - "close"
      - condition: "perm *ap.法师"
        display:
          material: "<head:%player_name%>"
          name: "&e个人信息"
          lore:
            - "&r"
            - "&8| &7当前职业: &6法师"
            - "&8| &7重置价格: &e5000$"
            - "&r"
            - "&8| {ke: if money *5000 then *&e&l✔点击重置职业 else *&c&l✖你没有足够的金币}"
            - "&r"
          flags:
            - "HIDE_ENCHANTS"
            - "HIDE_ATTRIBUTES"
            - "HIDE_UNBREAKABLE"
            - "HIDE_POTION_EFFECTS"
            - "HIDE_DESTROYS"
            - "HIDE_PLACED_ON"
        actions:
          all:
            - "sound: UI_BUTTON_CLICK-1-1"
            - condition: "money *5000"
              actions:
                - "take-money: 5000"
                - "console: lp user %player_name% permission unset ap.法师"
                - "tell: &8[&6SYSTEM&8] &c职业已重置！"
                - "close"
              deny:
                - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法重置职业"
                - "close"
      - condition: "perm *ap.游侠"
        display:
          material: "<head:%player_name%>"
          name: "&e个人信息"
          lore:
            - "&r"
            - "&8| &7当前职业: &6游侠"
            - "&8| &7重置价格: &e5000$"
            - "&r"
            - "&8| {ke: if money *5000 then *&e&l✔点击重置职业 else *&c&l✖你没有足够的金币}"
            - "&r"
          flags:
            - "HIDE_ENCHANTS"
            - "HIDE_ATTRIBUTES"
            - "HIDE_UNBREAKABLE"
            - "HIDE_POTION_EFFECTS"
            - "HIDE_DESTROYS"
            - "HIDE_PLACED_ON"
        actions:
          all:
            - "sound: UI_BUTTON_CLICK-1-1"
            - condition: "money *5000"
              actions:
                - "take-money: 5000"
                - "console: lp user %player_name% permission unset ap.游侠"
                - "tell: &8[&6SYSTEM&8] &c职业已重置！"
                - "close"
              deny:
                - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法重置职业"
                - "close"
      - condition: "perm *ap.炮手"
        display:
          material: "<head:%player_name%>"
          name: "&e个人信息"
          lore:
            - "&r"
            - "&8| &7当前职业: &6炮手"
            - "&8| &7重置价格: &e5000$"
            - "&r"
            - "&8| {ke: if money *5000 then *&e&l✔点击重置职业 else *&c&l✖你没有足够的金币}"
            - "&r"
          flags:
            - "HIDE_ENCHANTS"
            - "HIDE_ATTRIBUTES"
            - "HIDE_UNBREAKABLE"
            - "HIDE_POTION_EFFECTS"
            - "HIDE_DESTROYS"
            - "HIDE_PLACED_ON"
        actions:
          all:
            - "sound: UI_BUTTON_CLICK-1-1"
            - condition: "money *5000"
              actions:
                - "take-money: 5000"
                - "console: lp user %player_name% permission unset ap.炮手"
                - "tell: &8[&6SYSTEM&8] &c职业已重置！"
                - "close"
              deny:
                - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法重置职业"
                - "close"
  "A":
    update: 1
    display:
      material: "DIAMOND_AXE"
      name: "&e战士"
      lore:
        - "&r"
        - "&8| &7每次输出: &a偏高"
        - "&8| &7每秒输出: &a中"
        - "&8| &7防御坦度: &a中"
        - "&8| &7攻击频率: &a偏低"
        - "&8| &7购买价格: &e10$"
        - "&r"
        - "&8| {ke: if money *10 then *&e&l✔点击购买职业 else *&c&l✖你没有足够的金币}"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
        - condition: "money *10"
          actions:
            - "take-money: 10"
            - "console: lp user %player_name% permission set ap.战士"
            - "tell: &8[&6SYSTEM&8] &6你已选择&c“战士”&6职业"
            - "close"
          deny:
            - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法选择职业"
            - "close"
  "B":
    update: 1
    display:
      material: "DIAMOND_SWORD"
      name: "&e刺客"
      lore:
        - "&r"
        - "&8| &7每次输出: &a高"
        - "&8| &7每秒输出: &a高"
        - "&8| &7防御坦度: &a低"
        - "&8| &7攻击频率: &a偏低"
        - "&8| &7购买价格: &e30$"
        - "&r"
        - "&8| {ke: if money *30 then *&e&l✔点击购买职业 else *&c&l✖你没有足够的金币}"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
        - condition: "money *30"
          actions:
            - "take-money: 30"
            - "console: lp user %player_name% permission set ap.刺客"
            - "tell: &8[&6SYSTEM&8] &6你已选择&c“刺客”&6职业"
            - "close"
          deny:
            - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法选择职业"
            - "close"
  "C":
    update: 1
    display:
      material: "NETHERITE_CHESTPLATE"
      name: "&e坦克"
      lore:
        - "&r"
        - "&8| &7每次输出: &a低"
        - "&8| &7每秒输出: &a低"
        - "&8| &7防御坦度: &a超高"
        - "&8| &7攻击频率: &a偏低"
        - "&8| &7购买价格: &e10$"
        - "&r"
        - "&8| {ke: if money *10 then *&e&l✔点击购买职业 else *&c&l✖你没有足够的金币}"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
        - condition: "money *10"
          actions:
            - "take-money: 10"
            - "console: lp user %player_name% permission set ap.坦克"
            - "tell: &8[&6SYSTEM&8] &6你已选择&c“坦克”&6职业"
            - "close"
          deny:
            - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法选择职业"
            - "close"
  "D":
    update: 1
    display:
      material: "BLAZE_ROD"
      name: "&e法师"
      lore:
        - "&r"
        - "&8| &7每次输出: &a高"
        - "&8| &7每秒输出: &a偏高"
        - "&8| &7防御坦度: &a偏低"
        - "&8| &7攻击频率: &a中"
        - "&8| &7购买价格: &e20$"
        - "&r"
        - "&8| {ke: if money *20 then *&e&l✔点击购买职业 else *&c&l✖你没有足够的金币}"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
        - condition: "money *20"
          actions:
            - "take-money: 20"
            - "console: lp user %player_name% permission set ap.法师"
            - "tell: &8[&6SYSTEM&8] &6你已选择&c“法师”&6职业"
            - "close"
          deny:
            - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法选择职业"
            - "close"
  "E":
    update: 1
    display:
      material: "CROSSBOW"
      name: "&e游侠"
      lore:
        - "&r"
        - "&8| &7每次输出: &a中"
        - "&8| &7每秒输出: &a超高"
        - "&8| &7防御坦度: &a低"
        - "&8| &7攻击频率: &a超高"
        - "&8| &7购买价格: &e50$"
        - "&r"
        - "&8| {ke: if money *50 then *&e&l✔点击购买职业 else *&c&l✖你没有足够的金币}"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
        - condition: "money *50"
          actions:
            - "take-money: 50"
            - "console: lp user %player_name% permission set ap.游侠"
            - "tell: &8[&6SYSTEM&8] &6你已选择&c“游侠”&6职业"
            - "close"
          deny:
            - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法选择职业"
            - "close"
  "F":
    update: 1
    display:
      material: "BOW"
      name: "&e炮手"
      lore:
        - "&r"
        - "&8| &7每次输出: &a超高"
        - "&8| &7每秒输出: &a超高"
        - "&8| &7防御坦度: &a低"
        - "&8| &7攻击频率: &a偏低"
        - "&8| &7购买价格: &e70$"
        - "&r"
        - "&8| {ke: if money *70 then *&e&l✔点击购买职业 else *&c&l✖你没有足够的金币}"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
        - condition: "money *70"
          actions:
            - "take-money: 70"
            - "console: lp user %player_name% permission set ap.炮手"
            - "tell: &8[&6SYSTEM&8] &6你已选择&c“炮手”&6职业"
            - "close"
          deny:
            - "tell: &8[&6SYSTEM&8] &c你的金币不足，无法选择职业"
            - "close"

第二个
Title: "&8主要菜单: %player_name%"
Layout:
  - "#########"
  - "#A#EFGHI#"
  - "#B#######"
  - "#C#01234#"
  - "#D#56789#"
  - "#########"
Bindings:
  Items:
    - "material:clock"
Icons:
  "#":
    update: 1
    display:
      material: BLACK_STAINED_GLASS_PANE
      name: " "
    actions:
      all:
        - "sound: UI_BUTTON_CLICK-1-1"
  "5":
    update: 1
    display:
      material: "CROSSBOW"
      name: "&e&l职业选择"
      lores:
        - "&r"
        - "&8| &7所有的武器都必须要拥有职业才可以"
        - "&8| &7使用，并且也是服务器最主要的玩法"
        - "&8| &7之一。还在等什么？快选择职业吧！"
        - "&r"
        - "&8| &e&l✔点击使用此功能"
        - "&r"
      flags:
        - "HIDE_ENCHANTS"
        - "HIDE_ATTRIBUTES"
        - "HIDE_UNBREAKABLE"
        - "HIDE_POTION_EFFECTS"
        - "HIDE_DESTROYS"
        - "HIDE_PLACED_ON"
    actions:
      all:
        - "close"
        - "menu: 职业选择"
        - "sound: UI_BUTTON_CLICK-1-1"
```
