### ISSUE TITLE
[问题]: 图标节点变量在大小写图标ID中无法正常工作

### ISSUE THREAD

**Issue by Dirt233** [InsinuateProjects/TrMenu#201]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-07-03 20:52:17)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-1620 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_301

| TrMenu: 3.1.11
Installed Plugins: 
· AlwaysDay - 2.2.8 (0 KB)
· AntiWDL - 1.0 (0 KB)
· AuthMe - 5.6.0-beta2-b2453 (0 KB)
· AuthMeGUI - 1.1.1-1.12.2-R0.1-SNAPSHOT (0 KB)
· AutoRestart - 4.2.1 (0 KB)
· Citizens - 2.0.30-SNAPSHOT (build 2598) (0 KB)
· CommandNPC - 1.9.1 (0 KB)
· FastLogin - 1.11-SNAPSHOT-d802193 (0 KB)
· GlobalExecute - 1.0.1 (0 KB)
· HeadDatabase - 4.16.1 (0 KB)
· Helper - 1.0.0 (0 KB)
· HolographicDisplays - 3.0.0-SNAPSHOT (0 KB)
· JoinCommands - 2.0.6 (0 KB)
· LiteBans - 2.8.13 (0 KB)
· LuckPerms - 5.4.30 (0 KB)
· MyCommand - 5.7.2 (0 KB)
· NickNamer - 3.18.6-SNAPSHOT (0 KB)
· NoCheatPlus - 3.17-SNAPSHOT-Updated-b129 (0 KB)
· NoJoinQuitMessage - 2.3.3 (0 KB)
· NoRain - 1.6 (0 KB)
· PacketListenerApi - 3.7.9-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerBalancerAddon - 2.3.1-SNAPSHOT (0 KB)
· ProtocolLib - 4.6.0 (0 KB)
· StopFallDamage - 1.0 (0 KB)
· SuperAntiChat - 1.0.0 (0 KB)
· TigerReports - 5.0.16 (0 KB)
· TpLogin - 3.1 (0 KB)
· TrMenu - 3.1.11 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 4.3.1 (0 KB)
· ViaRewind - 2.0.2 (0 KB)
· ViaVersion - 4.3.1 (0 KB)
· Void2Spawn - 1.1.0 (0 KB)
· WorldBorder - 1.8.7 (0 KB)
· Yum - 2.9.5-git-18dc99e78ee6c087da72f944be32e90e5c93b3a5 (0 KB)
```

### 🔍 详细的描述

```
图标ID一个为a一个为A
在A的图标中使用{node: Icons.@iconid@.description.version}变量，只能获得a的节点内容
配置详见下面
```

### 🗄 服务端日志

```
[20:50:53 INFO]: [TrMenu] 良好 | 自动重新载入菜单 Select.yml (11ms)
```

### ⚙ 配置文件

```
a:
    description:
      version: All
    update: 80
    display:
      material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIzYWM5M2Q1ZTk5OTVkZTg0YWE5NWRlM2M4OWU0MDQyNTYwNjAzNGRkOGQ3NWNmZDcxOTYxNjA5YmQ1MjgxNSJ9fX0=
      name: '&e主大厅&7（&6推荐!&7{node: Icons.@iconid@.description.version}）'
```
```
A:
    description:
      version: '1.8-1.12.2'
    update: 80
    display:
      material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTE5OTdkYTY0MDQzYjI4NDgyMjExNTY0M2E2NTRmZGM0ZThhNzIyNjY2NGI0OGE0ZTFkYmI1NTdiNWMwZmUxNCJ9fX0=
      name: '&e饥饿游戏&7（&6推荐!&7{node: Icons.@iconid@.description.version}）'
```
