### ISSUE TITLE
[问题]: TrMenu打开途中死亡，将无法再次打开菜单

### ISSUE THREAD

**Issue by Hiddenmn** [InsinuateProjects/TrMenu#208]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-07-23 15:10:38)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-387 (MC: 1.18.2) (1.18.2-R0.1-SNAPSHOT)
| Java version: 17.0.4

| TrMenu: 3.1.13
Installed Plugins: 
· AttributePlus - 3.2.9.3 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2536 (0 KB)
· AuthmeExpansion - 1.0.1 (0 KB)
· BlockLocker - 1.10.4 (0 KB)
· CMI - 9.2.1.4 (0 KB)
· CMIEInjector - 1.0.2.3 (0 KB)
· CMILib - 1.2.1.2 (0 KB)
· ConfigItem - 1.0.0 (0 KB)
· CoreProtect - 21.2 (0 KB)
· CustomForging - 1.2.0 (0 KB)
· GroupManager - 2.9 (Phoenix) (0 KB)
· Jobs - 5.1.0.0 (0 KB)
· LightAPI - bukkit-5.3.0 (build SNAPSHOT) (0 KB)
· LoneLibs - 1.0.20 (0 KB)
· Mcrmb - 2.0b19 (0 KB)
· McrmbShop - 1.0.7 (0 KB)
· McrmbVip - 1.0.7 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· MythicCrucible - 1.4.0 (0 KB)
· MythicLib - 1.3.1 (0 KB)
· MythicMobs - 5.1.0-f32e809c (0 KB)
· PistonMOTD - 5.0.1 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· QuickShop - 5.1.0.9 (0 KB)
· Residence - 5.0.1.7 (0 KB)
· TrMenu - 3.1.13 (0 KB)
· UltimateTimber - 2.3.3 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 4.3.1 (0 KB)
· ViaVersion - 4.3.1 (0 KB)
· WorldBorder - 2.1.5 (0 KB)
· WorldEdit - 7.2.10+1742f98 (0 KB)
```

### 🔍 详细的描述

```
1. TrMenu在打开的途中死亡

2. 之后不管进行任何的操作（包括再次死亡以及其他指令），都无法再次打开菜单

3. 目前探寻到的方法就是退出服务器重新进入后才可以打开TrMenu

（我死亡后打开再次打开菜单并没有报错什么的）
（我又用排除法试了一下只加载TRmenu和papi插件，还是这个情况，我认为应该就出在TRmenu的身上）
（现在又发现一个在这种情况下打开菜单的方法，就是打开另一个菜单，之后就能正常使用，不过之后如果打开菜单的途中死亡依然会遇到这个问题）

下面是复现视频以及复现完成后的后台截图

https://cowtransfer.com/s/eb22e69f5be44e

9fy66z

```

### 🗄 服务端日志

```
[latest.log](https://github.com/InsinuateProjects/TrMenu/files/9173303/latest.log)

```

### ⚙ 配置文件

```
Title:
  - '            &7&lLegendCraft'


Title-Update: -1

Layout:
  - - '####P###`Close`'
    - '12347   6'
    - '58    9ab'
    - '         '
    - '########`Next`'

  - - '########`Close`'
    - '         '
    - '         '
    - '         '
    - '`Pre`########'

PlayerInventory:
  - - '         '
    - '         '
    - '         '
    - '         '

Options:
  Arguments: false
  Default-Arguments: [ ]
  # Not work with animated title
  Free-Slots:
    - 71-73
  Default-Layout: 0
  Hide-Player-Inventory: false
  Min-Click-Delay: 200
  Depend-Expansions: [ 'server', 'player', 'progress', 'animations' ]

Bindings:
  Commands:
    - '(?i)menu(-)?(gui)?(s)?'
  Items:

Events:
  Open:
    - condition: 'perm *trmenu.use'
      actions:
        - 'sound: BLOCK_CHEST_OPEN-1-0'
  Close:
    - 'sound: BLOCK_CHEST_CLOSE-1-0'

Icons:
  '1':
    update: []
    display:
      material: Grass Block
      name: ['&e&l传送到主城']
      lore:
        - - '传送到主城'
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: spawn'
  '2':
    update: []
    display:
      material: Grass Block
      name: ['&e&l传送到资源']
      lore:
        - - '传送到资源'
        - - '禁止圈地以及放置任何贵重物品'
        - - '每个月定时刷新'
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: warp 资源的世界'
  '3':
    update: []
    display:
      material: NETHERRACK
      name: ['&e&l传送到地狱']
      lore:
        - - '传送到地狱'
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: warp 地下的世界'
  '4':
    update: []
    display:
      material: ENDER_STON
      name: ['&e&l传送到末地']
      lore:
        - - '目前暂未开放，等待玩家探索'
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: spawn'
  '5':
    update: []
    display:
      material: CAKE
      name: ['&e&l在线奖励']
      lore:
        - '每日在线奖励'
        - '总时长在线奖励'
        - '➥可以白嫖点券'
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: prewards'
  '6':
    update: []
    display:
      material: DIRT
      name: ['&e&l随机传送']
      lore:
        - '点击进行随机传送'

    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: rt'
  '7':
    update: []
    display:
      material: DIAMOND_SWORD
      name: ['&e&l传送到RPG']
      lore:
        - '积极建设中...'

    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: warp'
  '8':
    update: []
    display:
      material: GOLDEN_APPLE
      name: ['&e&l礼包']
      lore:
        - '可领取的礼包'
        - '➥活动礼包会放在这里'

    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: kit'
  '9':
    update: []
    display:
      material: DIAMOND
      name: ['&e&l抽奖商店']
      lore:
        - '点击进入抽奖商店'

    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: cjshop'
  'a':
    update: []
    display:
      material: EMERALD
      name: ['&e&lVIP商店']
      lore:
        - '点击进入VIP商店'

    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: VIPshop'
  'b':
    update: []
    display:
      material: GOLD_INGOT
      name: ['&e&l点券商店']
      lore:
        - '点击进入点券商店'

    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
        - 'command: dqshop'
        



  Close:
    update: [ -1, 5, -1, -1 ]
    display:
      material: Red Stained Glass Pane
      name: [ '&7&l关闭','&c&l关&7&l闭', '&c&l关闭' ]
    actions:
      all: close

  Next:
    update: [ -1, 5, -1, -1 ]
    display:
      material: Cyan Stained Glass Pane
      name: [ '&7&l下一页','&b&l下&7&l一页', '&b&l下一&7&l页', '&b&l下一页' ]
    actions:
      all:
        - 'page: 1'
        - 'sound: BLOCK_CHEST_OPEN-1-2'
  Pre:
    update: [ -1, 5, -1, -1 ]
    display:
      material: Lime Stained Glass Pane
      name: [ '&7&l上一页','&a&l上&7&l一页', '&a&l上一&7&l页', '&a&l上一页' ]
    actions:
      all:
        - 'page: 0'
        - 'sound: BLOCK_CHEST_OPEN-1-2'

  '#':
    update: []
    display:
      material: IRON_FENCE
      name: '待定'
      lore:
        - '&e&l待定'


  P:
    update: 20
    display:
      material: 'head:%player_name%'
      name: '&2&l%player_name%'
      lore:
        - ''
        - '&8&l| &7&l生命: &c%player_health_rounded% ♥'
        - '&8&l| &7&l等级: &3Lv.%player_level%'
        - ''
        - '&8&l| &7&lIP: &3%player_ip%'
        - '&8&L| &7&lPING: ${js: varInt("%player_ping%") < 60 ? "&a" : "&2"}%player_ping% ms'
        - ''
        - '&8&l➥ &7&l按下键盘上的6进行一个起飞'
        - '&8&l➥ &7&l记得在空地上使用'

    actions:
      all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      number_key_6:
        - 'close'
        - 'title: `&b&L3` &6&l3 10 20 40 &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-0'
        - 'title: `&3&L2` &6&l2 &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-0 {Delay=20}'
        - 'title: `&9&L1` &c&l1 &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-0 {Delay=40}'
        - 'js: player.setVelocity(player.getVelocity().setY(25)) &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-1 {Delay=50}'

  T:
    update: 20
    display:
      material: compass
      name: '&3&lTrMenu'
      amount: '${js: varInt("%server_time_s%") + 1}'
      lore:
        - ''
        - 'The following is the relevant statistics'
        - 'of TrMenu, from the bStats'
        - '&8(https://bstats.org/)'
        - ''
        - '&8| &3Servers: ${bStats.servers}'
        - '&8| &3Players: ${bStats.players}'
        - '&8| &3Menus: ${bStats.menus}'
        - ''
        - 'In the past half an hour,'
        - 'Menus have been opened ${bStats.opens} times'
        - ''



Tasks:
  tikTok:
    period: 80
    task:
      - condition: '$ sender.isOp()'
        actions:
          - 'sound: BLOCK_NOTE_BLOCK_BIT-1-2'

Functions:
  flash: |-
    function flash() {
      var display = new Date().getSeconds() % 2 == 0
      return display ? args[0] : "  "
    }
    flash()

  bStats:
    servers: vars("${bStats.query_servers_&a_&7 servers}")
    players: vars("${bStats.query_players_&6_&7 players}")
    menus: vars("${bStats.query_menus_&2_&7 menus}")
    opens: |-
      function opens() {
        var data = utils.query("https://bstats.org/api/v1/plugins/5742/charts/menu_open_counts/data?maxElements=1")
        if (data.has()){
          return "&b" + data.asJson().getAsJsonArray().get(0).getAsJsonArray().get(1) + "&7"
        }
        return "&8Loading." + vars("${flash_.}") + "&7"
      }
      opens()
    query: |-
      function query() {
        var data = utils.query("https://bstats.org/api/v1/plugins/5742/charts/" + args[0] + "/data?maxElements=1")
        if (data.has()){
          return args[1] + data.asJson().getAsJsonArray().get(0).getAsJsonArray().get(1) + args[2]
        }
        return "&8Loading." + vars("${flash_.}")
      }
      query()


```
