### ISSUE TITLE
节点配置中无法直接调用节点ID

### ISSUE THREAD

**Issue by wzq20010724** [InsinuateProjects/TrMenu#21]
在节点可配置的JS脚本中, 
没有办法直接调用该节点的节点ID. 
希望添加隐式参数的传入. 

示例节点: 
Icons:
  '节点ID':
    display:
      material: '{js: JS脚本}'
      name: '{js: JS脚本}'
      lore:
        - '{js: JS脚本}'
    actions:
      all:
      - condition: '{js: JS脚本}'
        actions:
        - 'js: 
          JS脚本;
          '

**Comment by Score2** [comment]
已在pre26添加，示例格式:
```
title: '{node: 自定义节点内容.test}, {node: 自定义节点内容.子节点.test}'

自定义节点内容:
  test: 1
  子节点:
    test: 333

Layout:
  - ''
  - '  1 B C '
  - ''

Icons:
  1:
    图标内的自定义节点内容:
      test: 111
      子节点:
        test: 2
    display:
      material: stone
      name: '{node: Icons.@iconid@.图标内的自定义节点内容.子节点.test}'
```
