### ISSUE TITLE
[Bug]: Sign catcher place a sign

### ISSUE THREAD

**Issue by Teyir** [InsinuateProjects/TrMenu#223]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: 2022-09-09 07:44:18)

| Server OS: Linux amd64 4.19.0-18-amd64
| Server software: git-Paper-65 (MC: 1.19) (1.19-R0.1-SNAPSHOT)
| Java version: 17.0.4

| TrMenu: 3.1.16
Installed Plugins: 
· AdvancedAchievements - 8.0.2 (0 KB)
· AdvancedCrates - 3.0.0-Pre2.1 (0 KB)
· BottledExp - 3.1.0.0 (0 KB)
· BuycraftX - 12.0.8 (0 KB)
· CMI - 9.2.2.0 (0 KB)
· CMILib - 1.2.2.0 (0 KB)
· Citizens - 2.0.30-SNAPSHOT (build 2632) (0 KB)
· Drop2InventoryPlus - 3.6.0 (0 KB)
· EpicFurnaces - 4.9.3-DEV_2 (0 KB)
· FastAsyncWorldEdit - 2.4.2-SNAPSHOT-247;a1babd5 (0 KB)
· FeatherBoard - 5.1.0 (0 KB)
· GamePoints - 1.3.1 (0 KB)
· HeadDatabase - 4.17.0 (0 KB)
· JetsHoppers - 3.3.10 (0 KB)
· JetsMinions - 7.6.4 (0 KB)
· Jobs - 5.1.0.0 (0 KB)
· LiteBans - 2.10.3 (0 KB)
· LuckPerms - 5.4.30 (0 KB)
· MobFarmManager - 2.0.3.0 (0 KB)
· Multiverse-Core - 4.3.2-SNAPSHOT-b870 (0 KB)
· NerfPhantoms - 1.3.0 (0 KB)
· NexEngine - 2.2.0 build-18/06/2022 (0 KB)
· OPSecurity - 2.4.2 (0 KB)
· One-AFK_SkyBlock - 1.0 (0 KB)
· One-Plugin - 1.0 (0 KB)
· PINPrompt - 3.3.2 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· Plan - 5.4 build 1722 (0 KB)
· PlayerPoints - 3.2.4 (0 KB)
· Quests - 4.5.1-b348 (0 KB)
· QuestsGUI - 0.46 (0 KB)
· QuickShop-Hikari - 3.0.2.4 (0 KB)
· RecyclerPlus - 1.1.4 (0 KB)
· RegisterCommands - 1.3.0 (0 KB)
· SkyGrades - 1.2 (0 KB)
· SkyVotes - 2.0-SNAPSHOT (0 KB)
· SqlLogger - 1.0 (0 KB)
· SuperiorSkyblock2 - 1.11.0.737 (0 KB)
· T2CodeLib - 12.5 (0 KB)
· TAB - 3.1.2 (0 KB)
· TrMenu - 3.1.16 (0 KB)
· UltimateTimber - 2.3.3 (0 KB)
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· WGEF-Reborn - 2.3-stable+6cd8b68 (0 KB)
· WeatherVote - 1.0.0 (0 KB)
· WildStacker - 3.8.0.322 (0 KB)
· WildTools - 2.13.0.68 (0 KB)
· WorldGuard - 7.0.7+216b061 (0 KB)
· dragonSpawn - ${project.version} (0 KB)
· spark - 1.9.20 (0 KB)
· zAuctionHouseV3 - 3.0.9.7 (0 KB)
```

### 🔍 Detailed description

```
This is a video with a demo of the bugg → https://youtu.be/-vIU57uxzZ4

```

### 🗄 Server log

```
Nothing append
```

### ⚙ Configurations

```
  'input':
    display:
      Name:
      - '&6Nombre custom'
      Lore:
      - ''
      - '&7Choisissez manuellement le nombre'
      - '&7d''items que vous souhaitez acheter'
      - ''
      Materials:
      - oak_sign
    actions:
      left:
      - catcher:
          amount:
            type: SIGN
            start: 'actionbar: &b&lMerci d''entrer le nombre d''items que vous souhaitez acheter, pour annuler taper: &8"&fcancel&8"'
            cancel: 'tell: &cAnnulation de l''action...'
            end:
              - 'open: shop_purchase {0} {1} {meta:input}'
              - 'delay: 10'
```
