### ISSUE TITLE
settings.yml中的Menu.Icon.Item.Default-Lore-Color设置无效

### ISSUE THREAD

**Issue by JinOuYongGu** [InsinuateProjects/TrMenu#55]
**Describe the bug**
将图标名称的默认颜色设置为&b
将lore的默认颜色设置为&a
发现lore的默认颜色不正确，变成了&b而不是&a
settings.yml中的对应位置：
```
Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&b"
      Default-Lore-Color: "&a"
      Pre-Color: false
```
游戏中的情况：
![image](https://user-images.githubusercontent.com/45219386/131317074-1cfdb75b-e61a-4bfb-aab6-eccc110026b4.png)

**To Reproduce**
1.将Default-Name-Color和Default-Lore-Color设置成2种不同的颜色
2.打开菜单
3.发现lore的颜色与name的颜色一样，设置中的内容无效

**Expected behavior**
![image](https://user-images.githubusercontent.com/45219386/131317253-1d198042-6ef9-41b5-89c2-5d0ed56f8cac.png)

**Screenshots**

正常情况↓
![image](https://user-images.githubusercontent.com/45219386/131317268-75535aba-27f7-4ee0-844b-331ea7488d12.png)

**Additional context**
trmenu版本为 - pre62
**2021.9.14更新：
尝试在paper1.16.5的最后一个版本(788版本)运行trmenu3 pre9的时候
该问题同样出现，即title颜色覆盖了lore颜色**

**Server Information**
```
TrMenu Dump Information:
https://paste.helpch.at/rudevabimu
