### ISSUE TITLE
I have a few questions and possibly bugs.

### ISSUE THREAD

**Issue by RE4ERKA** [InsinuateProjects/TrMenu#6]
### Does "update" work in lore?
Example:
```
  '1':
    update: 20
    display:
     material: grass_block
     lore:
     - ''
     - ' Placeholder: %player_name% '
     - ''
```
Placeholder is not updated unless plugin is reloaded. (also with "refresh")

### How does "ketherx" work?
Example:
```
  '1':
    update: 20
    display:
     material: emerald_block
     lore:
     - ''
     - ' &7Status quest&8: &f${ke: if permission *"quest1" then *"&aSuccessfully" else *"&eWait"}'
     - ''
```
This kether works, but by the way, "update" doesn't work either.

Now I specify kether like this:
```
    display:
      material: redstone_block
    actions:
      all: 'ke: particle normal "flame 0 0 0 -count 10" at location *world *0 *0 *0`'
```
Nothing happens, this is written in console:
![image](https://user-images.githubusercontent.com/66727581/128618186-5f03c661-620d-4954-893b-5aeaccca878b.png)
Not all are available or am I doing something wrong?

### Does "close" action work in "open" event?
```
Events:
  Open:
    actions:
      - 'message: text'
      - 'close'
```
Message is being written, but the menu does not close, there is nothing in console. (also with "force-close")

Server core: purpur
Server version: 1.17.1
There is the latest version of TrMenu and TabooLib.
I removed other plugins so that there were no conflicts.
