### ISSUE TITLE
Json message not working

### ISSUE THREAD

**Issue by kacperleague9** [InsinuateProjects/TrMenu#60]
**Describe the bug**
When i do
`        - 'json: §c§lOVERLORD §7» &f<Click here to get a link.@url=https://store.overlordmc.net@hover=Click for a link>'`
it doesnt work

**To Reproduce**
1. add a left click even with json message
2. message isnt sent

**Expected behavior**
Message should send i guess

```

| Server OS: debian
| Server software: purpur 1.17.1
| Java version: 16 hotspot

| TabooLib: 6
| TrMenu: 3.0-PRE-21
```

**Comment by 157946a** [comment]
The problem cannot be reproduced, can I record a video or GIF picture?

**Comment by kacperleague9** [comment]
https://gfycat.com/AnyBriefDassierat

**Comment by kacperleague9** [comment]
```
Title: ' '


Bindings:
  Commands: 'vote'

Events:
  Open:
    - 'sound: BLOCK_CHEST_OPEN-1-0'
Layout:
  - '|||||||||'
  - '|       |'
  - '| s   - |'
  - '| s   # |'
  - '|       |'
  - '|||||||||'

Icons:
  's':
    display:
      material: 'chest'
      name: '&cSite 1'
      lore:
      - ''
      - '&cClick for a link'
      actions: 
        left:
         - 'json: &3Hello, &b%player_name%&3, Buy Ranks on our &2&nstore@url=https://store.example.net &3site.'
  '#':
    update: 30
    display:
      material: ['feather{model-data=18}', 'feather{model-data=44}']
      name: ['&6Money LootCrate &7(T1)', '<g:#00AA00:#55FF55:#00AA00>Lucky Hat<g:#00AA00:#55FF55:#00AA00:l>']
      lores:
        - - ''
          - '&cChance: &f99%'
        - - ''
          - '&cChance: &f1%'
  '-':
    display:
      material: 'feather{model-data=18}'
      name: '&a&lVote Crate'
      lore:
       - ''
       - '&cChance: &f100%'
  '|':
    update: 10
    display:
      material: ['Green Stained Glass Pane', 'Lime Stained Glass Pane', 'Green Stained Glass Pane']
      name: ['&2&lVOTE', '&a&lVOTE', '&2&lVOTE']
```
