### ISSUE TITLE
[Bug]: data数据回档

### ISSUE THREAD

**Issue by Neige7** [InsinuateProjects/TrMenu#84]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have reviewed all existing issues, or a more detailed description of existing issues.

### 📰 Server details

```
TrMenu Dump Information (Date: 2021-10-08 22:05:33)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Purpur-1402 (MC: 1.17.1) (1.17.1-R0.1-SNAPSHOT)
| Java version: 16

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-RC-2
Installed Plugins: 
· CMI - 9.0.4.6 (0 KB)
· CMILib - 1.0.3.11 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· TrMenu - 3.0-RC-2 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
```

### 🔍 Detailed description

```
1. 安装并打开Bug测试菜单
2. 点击测试按钮
3. 输入指令/papi parse me %trmenu_data_test%, 发现该data的值已被设置为1
4. 立即退出服务器
5. 重新进入服务器, 并输入指令/papi parse me %trmenu_data_test%, 发现该data的值回滚为null
```

### 🗄 Server log

```

```

### ⚙ Configurations

```
Title:
  - '&fBUG&f&l测试'

Layout:
  - '         '
  - '    X    '
  - '         '

Icons:
  'X':
    display:
      material: 'STONE'
      name: '&f&l测试'
    actions:
      all:
        - 'set-data: test 1'
        - 'close'
```
