### ISSUE TITLE
[Bug]: The "amount" does not work correctly.

### ISSUE THREAD

**Issue by RE4ERKA** [InsinuateProjects/TrMenu#88]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: 2021-10-11 00:56:53)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Tuinity-"7d36676" (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
| Java version: 16.0.2

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-RC-2
Installed Plugins: 
· LuckPerms - 5.3.3 (0 KB)
· PlaceholderAPI - 2.10.9 (0 KB)
· TrMenu - 3.0-RC-2 (0 KB)
```
https://paste.helpch.at/dipafusiqu

### 🔍 Detailed description

```
I have started to work strangely "amount" and I decided to check what the problem is and found that the problem was in showing placeholder.

The bug is in additional "icons" which are shown in the true condition.

Below I showed in detail in the video, what the bug:
https://www.youtube.com/watch?v=aKlDOqK6DTs
```

### 🗄 Server log

```
[latest.log](https://github.com/InsinuateProjects/TrMenu/files/7317969/latest.log)
```

### ⚙ Configurations

```
Layout:
  - '    1'

Icons:
  '1':
    update: 10
    display:
      material: 'barrier'
    icons:
      - condition: 'check papi *%luckperms_meta_test% == *1'
        display:
          material: apple
          amount: 30
          lore:
          - ''
          - 'Any Placeholder causes an error in the amount:'
          - '%player_name%'
          - ''
```
[test.txt](https://github.com/InsinuateProjects/TrMenu/files/7317972/test.txt)
